### ISSUE TITLE
feature - "reset" trap

### ISSUE THREAD

**Issue by ChristophCaina** [unigas/swissinno_ble#3]
it would be cool to have the ability to reset the trap from within the integration after it detected a catch.
This is currently possible from within the app - but I haven't found a way how to do this from the integration

**Comment by unigas** [comment]
I will not pursue this at this time, if someone feels up to it please add it!

**Comment by unigas** [comment]
This does not work with just Bluetooth proxy, it is possible if you are using raspberry pi or via an ESP32 and ESPHome but then more hardware is required

**Comment by ChristophCaina** [comment]
Hi, thanks for the feedback.
I think, that this requires HomeAssistant to send something to the trap, right?

I am not very well into the whole Bluetooth thing or the development of integrations, but If I can figure out what's required to reset the trap I could maybe look into this when I have some time... :)

**Comment by unigas** [comment]
I have sent a question to them but yes it requires Home Assistant to send information to the trap, this can be done with an ESP32 etc but this makes it a much more complex integration

**Comment by ChristophCaina** [comment]
hm... shouldn't this be doable by a 'simple' button?
in theory - if HA can read the BT advertisments, it should also be able to send some? - if it is a specific with the device ID etc...

**Comment by unigas** [comment]
It is just the thing, as it is using Bluetooth proxy to read advertisment. Bluetooth proxy does not support sending messages.

**Comment by ChristophCaina** [comment]
hm... ok, understand.
But if it does not use the BT Proxy, but the built in BT Stack from HomeAssistant, it would work, right?
maybe, instead of a button entity, this could be implemented as a service / action, that could be called if required.
If you don't use a BT Proxy, it should work - correct?

**Comment by unigas** [comment]
Should work then yes, but this is listening to the BLE-proxy service, this would need a complete rebuild but if someone is interested in doing this work, go ahead!

**Comment by yz88** [comment]
Hi, here is my idea to implement the reset functionality in HA. In the `binary_sensor.py` file add the following code:

```
from homeassistant.helpers import entity_platform

...
async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry, async_add_entities):
    ....

    platform = entity_platform.async_get_current_platform()
    platform.async_register_entity_service(
        "reset_trap",
        {},  # no extra fields
        "async_reset_trap",
    )

class SwissinnoTrapSensor(BinarySensorEntity):
    ....
    async def async_reset_trap(self):
        """Manually reset the trap sensor to off."""
        self._state = False
        self.async_write_ha_state()
```
Then create a `services.yaml` file

```
reset_trap:
  name: Reset Trap
  description: Manually reset a Swissinno trap binary sensor to off.
  target:
    entity:
      domain: binary_sensor
  fields: {}
```

Then you can use a button on a dashboard to reset the trap

```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: binary_sensor.swissinno_trap_75030444
      - entity: sensor.swissinno_trap_battery_75030444
      - entity: sensor.swissinno_trap_rssi_75030444
    state_color: true
  - show_name: true
    show_icon: true
    type: button
    entity: binary_sensor.swissinno_trap_75030444
    name: Reset Trap
    icon: mdi:lock-reset
    tap_action:
      action: call-service
      service: swissinno_ble.reset_trap
      target:
        entity_id: binary_sensor.swissinno_trap_75030444
    icon_height: 50px
grid_options:
  columns: 12
  rows: 6
title: Mausfallen
```
